### ISSUE TITLE
Benchmark results of uspt

### ISSUE THREAD

**Issue by hosseinfani** [fani-lab/OpeNTF#119]
We need to include the results of our 16+1 baselines on uspt

**Comment by karan96** [comment]
This is to notify you that this issue was acknowledged and we will be performing the benchmark for USPT during the coming week.

**Comment by karan96** [comment]
@hosseinfani 
Benchmarking of the USPT was started. No NS and Uniform was completed and Unigram was in progress.

**Comment by hosseinfani** [comment]
@karan96 would you please update this page with the running settings of the benchmark? Thank you.

**Comment by karan96** [comment]
@hosseinfani Dr. Fani,
Kindly let me know if you were able to review the benchmark excel I shared with you, so that I could put it into the format same as other datasets' images on our readme section.

**Comment by hosseinfani** [comment]
@karan96 I left my comments in your ms-team channel. Also here:
Thank you. Here are my comments:
1) there are some absolute 0 in cells. Please investigate why?
2) the AUC tab does not have the results of uspt
3) please create a table for uspt in Paper tab
4) where is the results of random baseline?

**Comment by hosseinfani** [comment]
An aggregate function has been added to main.py that pulls all the results and put them in an organized csv for each domain.
We can safely close this issue.
