### ISSUE TITLE
Preprocessing raw data into Sparse Matrix

### ISSUE THREAD

**Issue by hosseinfani** [fani-lab/OpeNTF#147]
@gabrielrueda 
In order to make the raw data ready for machine, we do preprocessing and store the data into a sparse matrix. 
Please study how we do this in our codeline. 
You can study #79 for more info.

**Comment by gabrielrueda** [comment]
Hi @hosseinfani,
Here is an update of what I have done so far:
- Downloaded the required python packages for the project on my computer
- Opened the pfl file of teamsvecs.pkl
- Printed out the skill values and member values
- Wrote the output of the src-dataset.txt like the comment from #79: https://github.com/fani-lab/OpeNTF/issues/79#issuecomment-977474405.
- Looked into how to split a dataset in python with sklearn

I have a question regarding https://github.com/fani-lab/OpeNTF/issues/79#issuecomment-976914804:
What is the output we are trying to get for tgt-dataset.txt and how does that different from src-dataset.txt. 

For the src-dataset.txt I have generated some differerent values as the screenshots in issue #79:
![image](https://user-images.githubusercontent.com/35504507/167449342-0c4d778d-1fb0-49cf-b293-b8bcd7e2f66f.png)
I was wondering if the values of the sparse matrix have changed or if I am on the wrong track. 

Finally, here is the code thus far:
```Python
with open('data/preprocessed/dblp/toy.dblp.v12.json/teamsvecs.pkl', 'rb') as tfile: 
    matrix=pickle.load(tfile)


X = matrix['skill']
y = matrix['member']


print("Skill:")
print(X)

print("Member:")
print(y)

f = open("src/src-dataset.txt","wt")

# Generate the src-dataset.txt file
for i in range(0,30):
    out = (X.getrow(i).asformat("array"))[0]
    for j in range(0,len(out)):
        if(out[j] == 1.0):
            f.write(str(j) + " ")
    f.write("\n")
```

**Comment by hosseinfani** [comment]
Hi  @gabrielrueda ,
Thanks for the update. 
You don't need to go over the split. As far as you know the internal structure of the space matrix, you're good for the next step.

As you see, each row of the sparse matrix show a `team` and has two main parts: skills and members. The content of the rows are the indexes of skills and members that belong to that team. E.g.,

```
[id][skill] [member]
[5 ][0 , 0, 0, 1, 0, 0, 1, 0] [1 , 1, 0, 0, 1] #we have a team with id=5, where the skills are {s3,s6} and the members are {m1,m2,m5} 

```
When it becomes sparse matrix, we only store the index of non-zero values to save space. So, the team is actually this:
`[id:5][skills:3,6][members:1,2,5]`

You may ask what are skills 3 or 6?
Or you may ask what are members 1, 2, 6? 

If you want to know the actual names of skills or the actual names of members, there is another file called `indexes.pkl` next to the `teamsvecs.pkl`. 

Please try to load this file and see what are the content and keep me updated here.

**Comment by gabrielrueda** [comment]
Hi @hosseinfani, 
I loaded the indexes.pkl file and noticed that the members were 1_hinton, 2_bengio, 3_lecun,  the skills were image_captioning, deep_learning, image_processing, and the teams were 1,2,3,4...., 30,31.
In the file you could either retrieve a skill, member or team using an index number or vice-versa. 


So, I modified the code I created to print out each team with their members and skills to better understand the content of the rows.

For example, the eleventh row would look like this
[10] [0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, ] [0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, ]

which means that...
Team #11; Skills: language_modelling, machine_learning, debiasing, ; Members: 2_bengio, 7_norvig, 

Here is the code for that:
```Python
# Generate the src-dataset.txt file
for i in range(0,30):
    f.write("Team #" + str(i+1) + "; ")

    f.write("Skills: ")
    out = (X.getrow(i).asformat("array"))[0]
    for j in range(0,len(out)):
        if(out[j] == 1.0):
            f.write(indexes['i2s'][j] + ", ")
    
    f.write("; Members: ")
    out = (y.getrow(i).asformat("array"))[0]
    for j in range(0,len(out)):
        if(out[j] == 1.0):
            f.write(indexes['i2c'][j]+ ", ")

    f.write("\n")

f.write("---\n")

# Generate the src-dataset.txt file
for i in range(0,30):
    f.write("[" + str(i) + "] ")
    f.write("[")
    out = (X.getrow(i).asformat("array"))[0]
    for j in range(0,len(out)):
        if(out[j] == 1.0):
            f.write("1, ")
        else:
            f.write("0, ")
    
    f.write("] [")
    out = (y.getrow(i).asformat("array"))[0]
    for j in range(0,len(out)):
        if(out[j] == 1.0):
            f.write("1, ")
        else:
            f.write("0, ")

    f.write("]\n")

 ```

**Comment by hosseinfani** [comment]
@gabrielrueda 
- Now, you got a good understanding of the sparse matrix and the semantics of it. We can move forward to the next task about counting the collaborations (#117). 

If you agree, we can close this issue.

**Comment by gabrielrueda** [comment]
@hosseinfani Yes, I will close the issue, and move on to counting the collaborations.
