### ISSUE TITLE
2021 - CIKM - RW-Team Robust Team Formation using Random Walk

### ISSUE THREAD

**Issue by VaghehDashti** [fani-lab/OpeNTF#154]
**Title**: [RW-Team: Robust Team Formation using Random Walk](https://dl.acm.org/doi/10.1145/3459637.3481969)
**Year**: 2021
**Venue**: CIKM

**Introduction**:
	An expert network contains professionals with their skills and their collaboration with other experts. There has been a surge of interest in forming teams of experts in expert networks.

**Main problem**:
	Given an expert network and a project that requires a set of skills, what is the most effective team?
**Example**:
	    
![image](https://user-images.githubusercontent.com/80131857/170730922-db069db6-8be4-49be-a67e-876dc2904fd0.png)
![image](https://user-images.githubusercontent.com/80131857/170730937-0627447c-5f76-4923-a80d-968ea2f6ba5e.png)

**Input**:
	A set of skills

**Output**:
	A team of experts

**Motivation**:
	Forming teams of experts that consider the structure of the graph

**Previous works and their gaps**:
	They use the shortest paths between experts as an indicator of communication cost and try to minimize that, but they ignore the structure of the graph.

**Contribution of this paper**:
	 They proposed a random walk with restarts for team formation, that can better capture the structure of the graph. They have provided a distributed implementation of their work and previous shortest path-based works. Finally, they implemented a visualization for the random walk.

**Proposed Method**:
	Random walk with restarts from the expert with the rarest skill needed for the project
 
![image](https://user-images.githubusercontent.com/80131857/170731327-0b1dba3e-3fc2-4e92-905e-cbe1f9f57f9f.png)

**Experiments**:
	No results were provided. 

**Code**:
      [http://data.science.uoit.ca:8180/TeamFormation-demo](http://data.science.uoit.ca:8180/TeamFormation-demo)

**Gaps of this work**:
- They didn’t show whether the teams created by their method will be successful by comparing with observed successful teams
- They represent human collaboration statically, while people collaborate with different people at different times
- Some of the hyperparameters are not mentioned (number of steps, number of surfers)

**Comment by hosseinfani** [comment]
@VaghehDashti 
please explain your understanding of the team formation from the proposed algorithm. I'm not sure I understood how the team is formed using random walk on the collaborative network.
