### ISSUE TITLE
2022: CIKM : OpeNTF: A Benchmark Library for Neural Team Formation

### ISSUE THREAD

**Issue by Hamedloghmani** [fani-lab/OpeNTF#172]
**Title: [OpeNTF: A Benchmark Library for Neural Team Formation]**(https://hosseinfani.github.io/res/papers/A%20Benchmark%20Library%20for%20Neural%20Team%20Formation.pdf)
Year: 2022
Venue: CIKM

**Main Problem**
The main goal of this research is to obtain a benchmark library for the given problem namely, “Neural Team Formation”. To put the team formation problem in a nutshell, with a set of required skills as input, we want to determine a set of experts as output with maximum chance of success in that specific project.

**Proposed Approach**
They came up with an automated pipeline (without a human in the loop) based on Pytorch that manage to do the process of pre-processing, training and evaluation with a single starting act. The main neural architecture could be based on feed-forward neural networks or Bayesian neural networks. Notably, hyperparameters of the architecture are customizable. Their method utilizes negative sampling heuristics to boost their performance (since there is a lack of negative samples in their dataset). In this specific domain, negative samples are the teams that failed to successfully accomplish the task (publishing a paper for instance or selling a movie more than a threshold) while positive samples are the opposite. 
As a result of the nature of the given problem and one-hot encoding, the representation of data samples would be sparse matrixes initially. As an alternate, the dense vector representation was offered where they developed a class namely, Team2Vec.  They utilized Doc2Vec model. Doc2vec is an NLP tool and a generalization of the word2vec method. It is used to create a vectorized representation of a group of words taken collectively as a single unit.

**Input**
Dense or Sparse Matrix representation of required skills.

**Output**
Dense or Sparse matrix representation of experts

**Cons**
1) Very limited choice of neural architectures at the moment (feed forward and Bayesian)
2) Mediocre performance (based on the metrics published in the papers GitHub repo)
3) Usage of closed-world assumption
 
**Gaps of Existing Alternatives**
1) Lack of the ability to generalize properly on big and real-world datasets
2) Not providing a robust pipeline without a human in the loop

**Datasets**
IMDb Datasets
PatentsView
dblp.v12

**Code**
https://github.com/fani-lab/OpeNTF

**Comment by hosseinfani** [comment]
@Hamedloghmani 
gaps of current work? gaps of existing works? what is dense vector and how is it calculated? what we mean by negative or positive  samples?

**Comment by Hamedloghmani** [comment]
@hosseinfani 
Thanks. I updated the text based on your comments.
I was not sure ( still not sure) how detailed should my explanations be.

**Comment by hosseinfani** [comment]
@Hamedloghmani 
you'll get it. 
Btw, 1 short paper (which was fully explained by me ;) in a week is very scarce. 
Also, how about other tasks like installation ...
We'll talk tomorrow.

**Comment by Hamedloghmani** [comment]
@hosseinfani 
You're totally right.
I'll explain tomorrow.
