### ISSUE TITLE
2020: CIKM: Learning to Form Skill-based Teams of Experts

### ISSUE THREAD

**Issue by Hamedloghmani** [fani-lab/OpeNTF#176]
**Title**: [Learning to Form Skill-based Teams of Experts](https://dl.acm.org/doi/10.1145/3340531.3412140)
**Year**: 2020
**Venue**: CIKM

**Main Problem**
The aim of this research is to find an optimal team of experts for a project with specific set of required skills to maximize the chance of their success.

**Related Works**
This problem was first tackled by [1] where the authors came up with an optimization-based approach for the issue and it was just based on the communication cost of a team that was naïve. In [2] they tried to consider personnel costs in addition to the communication cost when the project has a fixed budget. These notable related works have certain drawbacks. First, their computational cost is expensive since they use graph-based methods for finding paths on a large network. Second, their result might be sub-optimal. Third, when the number of participations between experts is small compared to the network size, or when the network is sparse, they fall short. Finally, they lack the ability to scale to real-world usage.
Authors claim that [3] is the only work until that date that used neural architecture to address the team formation problem. Although usage of non-variational auto-encoder makes it prone to overfitting and with the sparsity in the training data this would be more relatable.

**Proposed Method**
They suggest using a variational Bayesian neural architecture where instead of static weights, the distribution for each weight in the network is learned. Instead of using a network representation, they considered each team with a collaboration history as a training sample. To create a vector representation, they utilized two approaches, first the occurrence vector (which is basically the one-hot representation of a subset of skills) and dense vector representation (I did not get this part and still working on it). Also, they looked at the task of team formation as kind of a recommendation system problem. Hence, for collaborative filtering purposes, they adopted the rnn structure from [4]. The bin and factor size were determined by grid search and other parameters were set to default.

**Major Gaps**
In my opinion, there are a few major drawbacks to this research. First, the temporality is not addressed. Second, this work is prone to bias since fairness is not tackled here. Third, many other important factors play a key role in the success of a team such as personality and psychological aspects and they are not considered here.

**Input**
Vector representation of required skills.

**Output**
Vector representation of recommended experts

**Dataset**
Dblp

**Codebase**
https://anonymous.4open.science/r/b8584256-b23a-42a1-8e8b-b901826c475c/readme.md

References
[1] T. Lappas, L. Liu, and E. Terzi. 2009. Finding a Team of Experts in Social Networks. In KDD. 467 476
[2] M. Kargar, M. Zihayat, and A. An. 2013. Finding Affordable and Collaborative Teams from a Network of Experts. In SDM. 587–595
[3] A. Sapienza, P. Goyal, and E. Ferrara. 2019. Deep Neural Networks for Optimal Team Composition. Frontiers in Big Data 2, 1 (2019), 1–13
[4] Chao-Yuan Wu, Amr Ahmed, Alex Beutel, Alexander J Smola, and How Jing. 2017. Recurrent recommender networks. In WSDM. 495–503

**Comment by hosseinfani** [comment]
@Hamedloghmani 
Good summary!

Please separate the gaps in a section.

**Comment by Hamedloghmani** [comment]
@hosseinfani 
Thanks a lot !
Sure, I updated the summary.
