### ISSUE TITLE
Wrappers for RRN and Caser to Plug them into the pipeline

### ISSUE THREAD

**Issue by hosseinfani** [fani-lab/OpeNTF#185]
@VaghehDashti 
Please add two wrappers for the rrn and caser baselines in the pipeline similar to opennmt, calling their code through command line (assuming the code is available at ./baseline folder.

**Comment by hosseinfani** [comment]
@VaghehDashti 
I see that you have completed these two wrappers. Thank you. Please link your pushes with the issue number so we can track the changes.

Some notes:
It's better to put the `with_zero` as an argument to the constructor:
https://github.com/fani-lab/OpeNTF/blob/b09c37d4a26303f2957a37590cfd7be1aec8fa69/src/mdl/rrn.py#L16

Also, is there any way to merge these two functions into one and decide base on `with_zero` option?
https://github.com/fani-lab/OpeNTF/blob/b09c37d4a26303f2957a37590cfd7be1aec8fa69/src/mdl/rrn.py#L22

Also, you said that for imdb, we have to run rrn `with_zero=True`. But in the main, it's not implemented:
https://github.com/fani-lab/OpeNTF/blob/b09c37d4a26303f2957a37590cfd7be1aec8fa69/src/main.py#L118

**Comment by VaghehDashti** [comment]
Hi @hosseinfani,
I fixed the rrn's constructor and prepare_data as mentioned above. Now the constructor gets the `with_zero` parameter, and the user can change it in the `param.py`. Please review and let me know.
About the imdb, should I remove the `with_zero` from `param.py` and put if else conditions relative to the dataset? or is the new implementation okay?

**Comment by hosseinfani** [comment]
@VaghehDashti 
Thank you. I close the issue but in case of bugs in future, please link/use this issue.
