### ISSUE TITLE
stats on uspt

### ISSUE THREAD

**Issue by hosseinfani** [fani-lab/OpeNTF#22]
Public link to download: https://patentsview.org/download/data-download-tables

Metadata (data dictionary) that explains the schema, columns, data types can be found at https://patentsview.org/download/data-download-dictionary

The main table is ``patent`` whose ``type`` column distinguishes different types of patents including: 
- utility
- design
- ...

Also, ``subgroup_id`` is the foreign key to ``cbc_subgroup`` that shows the category hierarchy of a patent like ``"Y10S706/XX"	"Data processing: artificial intelligence"``

**Stats:**

|``Utility`` Patents Stat| Value|
|-----|------|
|#Patents (teams)| 152,317|
|#Unique Inventors (members) |12,914|
|#Unique Subgroups (skills)|67,315|
|Avg #Inventors per Patent| 3.78|
|Avg #Subgroup per Patent |9.97|
|Avg #Patent per Inventor |6.95|
|Avg #Subgroup per Inventor |102.52|
|#Patent w/ Single Inventor|0|
|#Patent w/ Single Subgroup|8110|
|#Unique Inventor's Locations|261*|
|Avg Inventors' Locations per Patent|2.50|

*The Number of Unique Inventor's Locations is 261 which is substantially larger than the total number of countries in the world. One Possible explanation of this is could be because of the abbreviations used by USPT that might refer different codes for same countries or breaks down countries into different zones. The list extracted having unique abbreviations for countries from USPT dataset is as follows: - 
['AU', 'SR', 'DT', 'TJ', 'GA', 'CU', 'LU', 'CI', 'AL', 'TR', 'VN', 'EI', 'NL', 'GH', 'YU', 'SK', 'GP', 'MQ', 'KP', 'PS', 'NY', 'NR', 'BM', 'SM', 'TX', 'GY', 'TH', 'XH', 'PM', 'CN', 'BG', 'UY', 'GB', 'UZ', 'PF', 'LK', 'WA', 'SW', 'SN', 'MW', 'PH', 'BU', 'WV', 'PA', 'SG', 'ML', 'PY', 'OH', 'HR', 'LA', 'JP', 'HN', 'AD', 'AM', 'BI', 'CF', 'NE', 'BO', 'TV', 'HT', 'PR', 'IQ', 'BD', 'KZ', 'LC', 'SE', 'CO', 'VA', 'PW', 'NI', 'WL', 'DJ', 'IS', 'IL', 'SA', 'KE', 'GG', 'NF', 'BJ', 'PT', 'LI', 'MD', 'GD', 'AR', 'GM', 'DK', 'ZB', 'HK', 'EN', 'JA', 'ET', 'CT', 'CR', 'MC', 'BH', 'ZR', 'DE', 'TM', 'HU', 'AZ', 'CZ', 'NG', 'XK', 'ZW', 'YE', 'RU', 'un', 'XX', 'JO', 'MO', 'TA', 'IM', 'DD', 'AN', 'FI', 'CG', 'BB', 'AT', 'JE', 'TS', 'KS', 'KH', 'IN', 'ER', 'MA', 'BF', 'CK', 'AI', 'CL', 'BW', 'TW', 'TD', 'MS', 'HI', 'NC', 'US', 'BR', 'NP', 'SV', 'SU', 'GI', 'PK', 'DM', 'KG', 'DL', 'SD', 'RO', 'RP', 'AW', 'TN', 'LT', 'IO', 'RH', 'PE', 'FL', 'MI', 'FJ', 'BE', 'AG', 'SI', 'TO', 'GT', 'BQ', 'SF', 'CS', 'MU', 'TT', 'KN', 'PO', 'CY', 'TG', 'WI', 'NM', 'RS', 'AS', 'SY', 'ID', 'KR', 'SB', 'LR', 'ZM', 'AF', 'EE', 'CV', 'SO', 'SH', 'BY', 'UG', 'BZ', 'NZ', 'MH', 'BN', 'EC', 'GR', 'LY', 'MK', 'TK', 'AO', 'MN', 'EG', 'AP', 'IE', 'VT', 'SX', 'MG', 'DZ', 'KY', 'MP', 'MX', 'MM', 'GC', 'TC', 'GU', 'MT', 'VE', 'OM', 'SL', 'DO', 'TZ', 'GF', 'ZA', 'VU', 'FR', 'SZ', 'ES', 'KI', 'NO', 'SP', 'PG', 'JM', 'CM', 'OE', 'BS', 'CH', 'CW', 'QA', 'VG', 'FO', 'GN', 'SC', 'LV', 'EK', 'UA', 'VI', 'IR', 'BA', 'WS', 'MY', 'CA', 'ME', 'AE', 'MV', 'IT', 'RE', 'PL', 'KW', 'GL', 'LB', 'GE', 'RW', 'CD']

'nskills_country-idx': {'US': 63171146, 'KR': 6376367, 'DE': 7250590, 'MX': 74511, 'JP': 23445721, 'FR': 2589624, 'CN': 3105549, 'BE': 573012, 'IT': 977073, 'ES': 305570, 'IL': 1174175, 'GB': 2749343, 'DK': 390611, 'AT': 418750, 'CA': 2393098, 'CL': 14208, 'SE': 898928, 'PL': 68245, 'HK': 68462, 'AU': 805926, 'LI': 10471, 'CH': 1119272, 'MD': 210, 'NL': 933522, 'TW': 3446822, 'UA': 20459, 'IN': 955030, 'BR': 98035, 'NO': 154165, 'FI': 444805, 'SA': 145696, 'PT': 27633, 'JO': 2052, 'TR': 31199, 'AR': 26723, 'SG': 498889, 'CU': 12217, 'IE': 203752, 'NZ': 111227, 'ZA': 58395, 'TH': 29915, 'LU': 23795, 'MO': 1617, 'RS': 5270, 'RU': 196951, 'AM': 2538, 'CS': 3187, 'HU': 110528, 'CZ': 68140, 'MY': 106287, 'KY': 1694, 'RO': 20712, 'GR': 24400, 'QA': 3150, 'HR': 8297, 'SI': 12622, 'BN': 670, 'BO': 328, 'OM': 461, 'EE': 9801, 'MK': 169, 'MU': 75, 'LB': 2998, 'PK': 4109, 'AE': 12918, 'SK': 8492, 'PH': 31046, 'VN': 4447, 'BD': 1187, 'BG': 14385, 'NP': 91, 'CO': 7709, 'BS': 1874, 'IS': 14979, 'ID': 8003, 'PE': 1865, 'IR': 11049, 'GA': 128, 'BH': 608, 'LA': 13, 'JM': 837, 'LK': 2253, 'EG': 9273, 'BA': 542, 'DO': 611, 'KE': 2824, 'PS': 48, 'MA': 1103, 'LV': 7114, 'CR': 5158, 'KZ': 1155, 'KW': 4948, 'PY': 223, 'JE': 790, 'GE': 1166, 'LT': 5599, 'BY': 4385, 'DD': 2818, 'NG': 612, 'UY': 1622, 'CY': 2293, 'MT': 2071, 'SN': 81, 'GI': 390, 'MC': 3307, 'MN': 166, 'VE': 10050, 'TO': 8, 'EC': 884, 'AD': 326, 'GT': 547, 'AZ': 468, 'SL': 96, 'BZ': 147, 'WS': 290, 'TN': 985, 'YE': 150, 'SC': 1281, 'DZ': 275, 'BM': 841, 'UG': 191, 'SM': 63, 'SU': 76636, 'JA': 2515, 'TM': 56, 'IM': 620, 'AL': 48, 'SO': 3, 'PA': 982, 'DT': 11787, 'ET': 164, 'GL': 23, 'FO': 46, 'ML': 241, 'VG': 261, 'CD': 37, 'PF': 67, 'SY': 175, 'YU': 2833, 'TT': 1022, 'UZ': 282, 'ME': 146, 'ER': 37, 'AW': 148, 'MM': 104, 'ZW': 201, 'KP': 87, 'ZM': 50, 'DM': 52, 'SD': 32, 'CM': 250, 'PG': 38, 'CI': 46, 'BB': 359, 'CV': 15, 'HN': 307, 'GH': 478, 'MW': 27, 'NE': 163, 'SZ': 50, 'IQ': 160, 'SV': 110, 'GN': 31, 'AG': 193, 'AO': 90, 'TZ': 168, 'MG': 132, 'GF': 44, 'TC': 145, 'BI': 21, 'XK': 27, 'RW': 21, 'GD': 29, 'KN': 110, 'MH': 77, 'AI': 103, 'SX': 20, 'LC': 20, 'TD': 20, 'GP': 34, 'MQ': 9, 'KH': 83, 'NC': 47, 'MS': 13, 'EN': 1445, 'SW': 1092, 'ZB': 5, 'WA': 39, 'SF': 185, 'PO': 211, 'PM': 25, 'DL': 57, 'EI': 40, 'VI': 58, 'OE': 177, 'CT': 8, 'GU': 22, 'un': 181, 'EK': 5, 'HT': 73, 'GY': 74, 'FL': 6, 'RP': 16, 'TA': 2, 'RH': 44, 'KS': 11, 'SR': 16, 'TS': 1, 'WL': 2, 'PR': 423, 'BU': 15, 'NI': 77, 'GC': 12, 'AN': 45, 'LY': 47, 'MI': 12, 'CG': 8, 'LR': 27, 'XX': 3, 'AS': 4, 'HI': 1, 'BW': 19, 'NF': 30, 'VA': 108, 'IO': 49, 'TX': 4, 'WI': 33, 'VT': 3, 'OH': 4, 'WV': 4, 'SP': 2, 'BF': 59, 'NY': 5, 'NM': 1, 'CK': 15, 'KG': 44, 'ZR': 5, 'NR': 7, 'TK': 94, 'FJ': 40, 'XH': 10, 'GM': 115, 'PW': 3, 'AP': 12, 'MP': 5, 'BJ': 1, 'GG': 5, 'VU': 9, 'DJ': 26, 'AF': 14, 'RE': 17, 'KI': 9, 'SB': 6, 'TV': 3, 'MV': 39, 'CW': 7, 'SH': 1, 'CF': 3, 'TG': 8, 'TJ': 14, 'BQ': 2}, 'nmembers_country-idx': {'US': 8630848, 'KR': 830422, 'DE': 1159728, 'MX': 11218, 'JP': 3446296, 'FR': 401640, 'CN': 422769, 'BE': 72470, 'IT': 160646, 'ES': 41407, 'IL': 152372, 'GB': 381879, 'DK': 50126, 'AT': 62364, 'CA': 345625, 'CL': 2084, 'SE': 136043, 'PL': 10268, 'HK': 10583, 'AU': 86893, 'LI': 1677, 'CH': 160169, 'MD': 50, 'NL': 149449, 'TW': 473492, 'UA': 3150, 'IN': 144240, 'BR': 15917, 'NO': 25468, 'FI': 71379, 'SA': 14632, 'PT': 3211, 'JO': 296, 'TR': 4246, 'AR': 4372, 'SG': 45450, 'CU': 1247, 'IE': 26720, 'NZ': 13467, 'ZA': 9798, 'TH': 3114, 'LU': 3747, 'MO': 290, 'RS': 607, 'RU': 29244, 'AM': 373, 'CS': 987, 'HU': 19254, 'CZ': 10260, 'MY': 11291, 'KY': 298, 'RO': 3201, 'GR': 3534, 'QA': 450, 'HR': 1065, 'SI': 2184, 'BN': 91, 'BO': 55, 'OM': 91, 'EE': 1212, 'MK': 28, 'MU': 14, 'LB': 347, 'PK': 669, 'AE': 1673, 'SK': 1319, 'PH': 2820, 'VN': 513, 'BD': 167, 'BG': 3074, 'NP': 17, 'CO': 1117, 'BS': 319, 'IS': 1718, 'ID': 697, 'PE': 273, 'IR': 1408, 'GA': 17, 'BH': 71, 'LA': 3, 'JM': 160, 'LK': 307, 'EG': 1497, 'BA': 57, 'DO': 112, 'KE': 367, 'PS': 18, 'MA': 190, 'LV': 566, 'CR': 703, 'KZ': 179, 'KW': 871, 'PY': 41, 'JE': 81, 'GE': 178, 'LT': 810, 'BY': 696, 'DD': 736, 'NG': 119, 'UY': 291, 'CY': 320, 'MT': 256, 'SN': 14, 'GI': 54, 'MC': 530, 'MN': 23, 'VE': 1975, 'TO': 4, 'EC': 132, 'AD': 46, 'GT': 83, 'AZ': 73, 'SL': 15, 'BZ': 25, 'WS': 37, 'TN': 160, 'YE': 20, 'SC': 345, 'DZ': 47, 'BM': 143, 'UG': 19, 'SM': 13, 'SU': 23892, 'JA': 662, 'TM': 8, 'IM': 73, 'AL': 8, 'SO': 1, 'PA': 134, 'DT': 3254, 'ET': 28, 'GL': 3, 'FO': 11, 'ML': 25, 'VG': 60, 'CD': 3, 'PF': 17, 'SY': 39, 'YU': 691, 'TT': 139, 'UZ': 67, 'ME': 26, 'ER': 4, 'AW': 17, 'MM': 15, 'ZW': 40, 'KP': 26, 'ZM': 6, 'DM': 5, 'SD': 9, 'CM': 45, 'PG': 10, 'CI': 10, 'BB': 61, 'CV': 1, 'HN': 52, 'GH': 47, 'MW': 6, 'NE': 26, 'SZ': 11, 'IQ': 25, 'SV': 35, 'GN': 4, 'AG': 31, 'AO': 13, 'TZ': 19, 'MG': 22, 'GF': 4, 'TC': 25, 'BI': 2, 'XK': 2, 'RW': 3, 'GD': 4, 'KN': 23, 'MH': 10, 'AI': 12, 'SX': 3, 'LC': 3, 'TD': 8, 'GP': 5, 'MQ': 2, 'KH': 9, 'NC': 14, 'MS': 1, 'EN': 390, 'SW': 305, 'ZB': 2, 'WA': 16, 'SF': 54, 'PO': 76, 'PM': 6, 'DL': 17, 'EI': 13, 'VI': 13, 'OE': 54, 'CT': 4, 'GU': 9, 'un': 48, 'EK': 1, 'HT': 15, 'GY': 9, 'FL': 2, 'RP': 7, 'TA': 1, 'RH': 13, 'KS': 2, 'SR': 4, 'TS': 1, 'WL': 1, 'PR': 101, 'BU': 3, 'NI': 12, 'GC': 2, 'AN': 18, 'LY': 11, 'MI': 4, 'CG': 3, 'LR': 4, 'XX': 1, 'AS': 2, 'HI': 1, 'BW': 4, 'NF': 12, 'VA': 13, 'IO': 5, 'TX': 3, 'WI': 7, 'VT': 1, 'OH': 2, 'WV': 1, 'SP': 1, 'BF': 21, 'NY': 1, 'NM': 1, 'CK': 6, 'KG': 10, 'ZR': 1, 'NR': 3, 'TK': 15, 'FJ': 6, 'XH': 2, 'GM': 4, 'PW': 1, 'AP': 3, 'MP': 2, 'BJ': 1, 'GG': 1, 'VU': 3, 'DJ': 4, 'AF': 4, 'RE': 3, 'KI': 1, 'SB': 1, 'TV': 1, 'MV': 1, 'CW': 1, 'SH': 1, 'CF': 1, 'TG': 1, 'TJ': 2, 'BQ': 1}
![nskills_country](https://user-images.githubusercontent.com/19558771/164598248-438feba0-f676-4bda-a1e6-f5344f925a4c.png)
![nmembers_country](https://user-images.githubusercontent.com/19558771/164598326-6b6fc47a-4190-4106-9fe2-074d146dd079.png)

**Comment by karan96** [comment]
The Issue was reopened during this week. The bug I faced is still there but I am continuing my efforts to resolve this asap. If in the case, I am not able to do that I will seek help.

**Comment by karan96** [comment]
@hosseinfani  The issues has been updated with filtered out stats and I have also added the comment to explain the larger number of unique countries. Kindly review and let me know if we are good to close this issue.

**Comment by karan96** [comment]
@hosseinfani Assuming that you had the time to review this issue hence, I am going to close this issue.

**Comment by hosseinfani** [comment]
@karan96 
No, I have not reviewed your code yet.

**Comment by karan96** [comment]
On Average a random patent is from how many countries

- Count number of unique countries in a patent
- Sum the count / Number of patents


2 unq - 1
3 unq - 2


pat,1 = 2 unq
pat,2 = 3 unq
.
.
.
pat,10 = 5 unq

If you randomly select one patent probably this is the number of unique countries in that patent	(2 + 3 + .... + 5)/10 
If you remove the uniqueness then it is same as average number of inventors as there is 1:1 association with countries

**Comment by Daljeet-sandhu** [comment]
Hello prof,
Here is my progress. I declared the location. I calculated the total number of locationsby using locationvecs.shape[1].
I also tried to determine the number of teams that have only 1 location, 2 locations, ..
![Screenshot (407)](https://user-images.githubusercontent.com/61301173/196563857-5252a812-eedb-4525-8263-fb26b093c07e.png)
Just wanted to get your confirmation regarding the code and functionalities that i am using.

Before working on the following, Do you want me to work on some other parameters?
![Screenshot (408)](https://user-images.githubusercontent.com/61301173/196563827-b93f3e6c-6a31-483d-a253-6de26f10cfdb.png)

Also please mention other parameters that you want me to work on.
Thanks, Daljeet

**Comment by hosseinfani** [comment]
@Daljeet-sandhu
I believe you're on the right track. 
We have a toy dataset for uspt: https://github.com/fani-lab/OpeNTF/blob/main/data/preprocessed/uspt/toy.patent.tsv/teamsvecs.pkl

You can test the correctness of the results by that.

**Comment by Daljeet-sandhu** [comment]
@hosseinfani  All right. Thanks.

**Comment by Daljeet-sandhu** [comment]
@hosseinfani 
I was able to complete following parameters:
For testing,(still a little confused)
Could you please let me know the steps or refer me to the document that explains the programs that i need to run step by step.
![Screenshot (411)](https://user-images.githubusercontent.com/61301173/197903633-5a2f2d7e-20fb-416f-8156-ec5fa1eb1989.png)

thanks

**Comment by hosseinfani** [comment]
@Daljeet-sandhu 
Thank you.
we have a piece of code that accept the sparse matrix and calls the Team.get_stat():
https://github.com/fani-lab/OpeNTF/blob/dev/src/misc/stats.py

You can pass the sparse matrix with the `plot=True` and `plot_title='the domain name'`. It outputs the single value stats and also draws the distributions in a pdf file. 

This way you can test your code on toy datasets available at 
`./data/preprocessed/{domain}/toy.*/teamsvecs.pkl`

Make sure that you work on the `dev` codeline.

**Comment by Daljeet-sandhu** [comment]
@hosseinfani 
Ok prof, I will work on the dev codeline.

What other parameter regarding the location that i should work on, next?

I did complete these:
#average number of people from each location
#how many members are from a particular location
#how many skills are from a particular location
# how many teams have only 1 location, 2 locations, ...

Please let me know.
Thank you

**Comment by hosseinfani** [comment]
@Daljeet-sandhu 
We also need these:

-How many members have only 1 location, 2 locations, ... ==> a person may be in different locations for different patents.
-we need a 3-d matrix (heatmap) with (x, y, z) where x: locations, y: skills, z: the number of patents (x, y). For example, we have `z=10` patents about `y=computer` that filed in `x=US` 
-we need a 3-d matrix (heatmap) with (x, y, z) where x: locations, y: members, z: the number of patents (x, y). For example, we have `z=10` patents for `y=hossein` that filed in `x=US` ==> this will be vary sparse I believe.

After testing on the toy example, put the results here.

**Comment by Daljeet-sandhu** [comment]
hello professor @hosseinfani , I am stuck and I need your help. I am free tomorrow - Wednesday throughout the day. Ping me for a meetup when free. thanks

**Comment by hosseinfani** [comment]
@Daljeet-sandhu 
I have classes on wednesdays.
How about tomorrow (thursday)? I'll on campus after noon till evening

**Comment by Daljeet-sandhu** [comment]
@hosseinfani 
I was able to work on both heatmap functions.
def loc_heatmap_skills(dataset)
def loc_heatmap_members(dataset):

But while testing,(through  stats.py)
I was receiving this error:
![Screenshot (434)](https://user-images.githubusercontent.com/61301173/202564795-7b0df2e8-f01f-4b82-826d-51ea7317fe99.png)
I installed param using pip install params, same error again.
I tried commenting out the line:
![Screenshot (432)](https://user-images.githubusercontent.com/61301173/202565152-f80a7aa5-55e1-4aed-9e5d-e6967e15b750.png)

Still no luck,


![Screenshot (431) - Copy](https://user-images.githubusercontent.com/61301173/202564726-7359def2-cccb-4caf-be10-37d556d2c923.png)


Would love your help on this.

**Comment by hosseinfani** [comment]
@Daljeet-sandhu 
`param` is not an external package. It's our code in /src/param.py. 
to run stats.py, you have to put your working directory at /src. Otherwise, it cannot find the internal files and packages. 
I donno have to change the working directory at shell. I usually run the stat.py in my ide.
